# Generated by Django 4.0.3 on 2022-03-03 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datosBasicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cliente_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datosBasicos.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('factura_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datosFactura.factura')),
                ('product_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datosBasicos.product')),
            ],
        ),
    ]
